author: ''
date: July 29, 2023
aim: ''
comparisons: ''
normalizations: ~
qc_cv_factor: ''
signal_heatmap: 'yes'
phosphosite_heatmap: ~
kinase_analysis: []
xax_scale: 'yes'
coral_ks_thr: 'coral_auto'
coral_min: -3
coral_max: 3
datatype: bionav
